# Generated by Django 3.1.14 on 2022-01-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220127_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
