# Generated by Django 3.1.14 on 2022-01-27 16:49

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
