# Generated by Django 3.1.14 on 2022-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20220127_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
