# Generated by Django 3.1.14 on 2022-01-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20220127_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
