# Generated by Django 3.1.14 on 2022-01-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20220128_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Aivler'), (1, 'Tutor')], default=0),
        ),
    ]
